export const subjects = {
    "Select": "0",
    "Aerospace Engineering": "AE",
    "Agricultural and Food Engineering": "AG",
    "Centre of Excellence in Artificial Intelligence (AI)": "AI",
    "Architecture and Regional Planning": "AR",
    "Advanced Technology Development Centre": "AT",
    "P.K. Sinha Centre for Bioenergy and Renewables": "BE",
    "Vinod Gupta School of Management": "BM",
    "Bio Science": "BS",
    "Bioscience and Biotechnology": "BT",
    "Centre for Computational and Data Sciences": "CD",
    "Civil Engineering": "CE",
    "Chemical Engineering": "CH",
    "Centre for Ocean, River, Atmosphere and Land Sciences (CORAL)": "CL",
    "Centre of Excellence in Public Policy, Law and Governance": "CP",
    "Cryogenic  Engineering": "CR",
    "Computer Science and Engineering": "CS",
    "Chemistry": "CY",
    "Deysarkar Centre of Excellence in Petroleum Engineering": "DE",
    "Centre of Excellence in Advanced Manufacturing Technology": "DH",
    "DRDO Industry Academia - Centre of Excellence (DIA-CoE)": "DR",
    "Centre of Excellence in Sustainable Development": "DS",
    "Electronics and Electrical Communication Engg.": "EC",
    "Electrical Engineering": "EE",
    "Environmental Science and Engineering": "EF",
    "Energy Science and Engineering": "ES",
    "Centre For Educational Technology": "ET",
    "Centre of Excellence in Advanced Transportation": "EX",
    "M. N. Faruqi Centre for Innovation": "FA",
    "Centre of Excellence in Affordable Healthcare": "FH",
    "Centre of Excellence in Precision Agriculture & Food Nutrition": "FN",
    "Geology and Geophysics": "GG",
    "G.S Sanyal School of Telecommunication": "GS",
    "Humanities and Social Sciences": "HS",
    "Ranbir and Chitra Gupta School of Infrastructure Design and Mngt.": "ID",
    "Industrial and Systems Engineering": "IM",
    "Rajiv Gandhi School of Intellectual Property Law": "IP",
    "School of Information Technology": "IT",
    "Centre of Excellence for Indian Knowledge Systems": "KS",
    "Mathematics": "MA",
    "Mechanical Engineering": "ME",
    "Mining Engineering": "MI",
    "School of Medical Science and Technology": "MM",
    "Materials Science Centre": "MS",
    "Metallurgical and Materials Engineering": "MT",
    "Ocean Engg and Naval Architecture": "NA",
    "Nano Science and Technology": "NT",
    "Physics": "PH",
    "Centre for Rural Development and Innovative Sustainable Technology": "RD",
    "Subir Chowdhury School of Quality and Reliability": "RE",
    "Rajendra Mishra School of Engg Entrepreneurship": "RJ",
    "Rubber Technology": "RT",
    "Rekhi Centre of Excellence for the Science of Happiness": "RX",
    "Education": "SD",
    "Centre of Excellence on Safety Engineering & Analytics (COE-SEA)": "SE",
    "Dr B C Roy Multi Speciality Medical Research Centre": "SH",
    "Steel Technology Centre": "SL",
    "Centre For Theoretical Studies": "TS",
    "Centre for Teaching Learning and Virtual Skilling": "TV",
    "Centre of Excellence in Urban Planning and Design": "UP",
    "School of Water Resources": "WM"
  };
  